// Generated by scripts/generate_scene_types.py from slide_scene_v1.schema.json (SHA-256 4cf040a434918c9b036b94d69a0276c70099947ce487e09e0ac368396109851c).
// Do not edit manually. These describe normalized server responses (defaults materialized).

export type Canvas = {
  width_pt: number;
  height_pt: number;
};

export type Crop = {
  x: number;
  y: number;
  w: number;
  h: number;
};

export type Frame = {
  x: number;
  y: number;
  w: number;
  h: number;
  rotation_deg: number;
};

export type ImageBackground = {
  kind: "image";
  asset_id: string;
  crop: Crop;
};

export type ImageElement = {
  id: string;
  kind: "image";
  role: "illustration" | "chart" | "icon" | "photo" | "decoration";
  asset_id: string;
  frame: Frame;
  crop: Crop;
  fit: "contain" | "cover";
  opacity: number;
  locked: boolean;
  alt_text: string;
};

export type SolidBackground = {
  kind: "solid";
  color: string;
};

export type TextElement = {
  id: string;
  kind: "text";
  role: "title" | "body" | "annotation";
  frame: Frame;
  text: string;
  style: TextStyle;
  locked: boolean;
};

export type TextStyle = {
  font_family_id: "noto-sans-sc";
  font_size_pt: number;
  font_weight: 400 | 700;
  color: string;
  align: "left" | "center" | "right";
  vertical_align: "top" | "middle" | "bottom";
  line_height: number;
  padding_pt: number;
};

export type SlideScene = {
  schema_version: 1;
  font_manifest_id: "fonts-v1";
  canvas: Canvas;
  background: SolidBackground | ImageBackground;
  elements: (TextElement | ImageElement)[];
};
