"""Generate normalized Scene TypeScript types from the server's JSON Schema.

Pydantic model_dump() materializes every schema field with a default, so those
fields are required in the normalized API response even when input permits
omitting them.
"""
import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'backend' / 'schemas' / 'slide_scene_v1.schema.json'
TARGET = ROOT / 'frontend' / 'src' / 'features' / 'editor' / 'slideScene.generated.ts'


def literal(value):
    return json.dumps(value, ensure_ascii=False)


def type_for(schema):
    if '$ref' in schema:
        return schema['$ref'].rsplit('/', 1)[-1]
    if 'const' in schema:
        return literal(schema['const'])
    if 'enum' in schema:
        return ' | '.join(literal(value) for value in schema['enum'])
    if 'oneOf' in schema:
        return ' | '.join(type_for(option) for option in schema['oneOf'])
    kind = schema.get('type')
    if kind == 'array':
        item = type_for(schema['items'])
        return f'({item})[]' if ' | ' in item else f'{item}[]'
    if kind == 'object':
        required = set(schema.get('required', []))
        lines = ['{']
        for name, field in schema.get('properties', {}).items():
            optional = '' if name in required or 'default' in field else '?'
            lines.append(f'  {name}{optional}: {type_for(field)};')
        lines.append('}')
        return '\n'.join(lines)
    if kind in ('integer', 'number'):
        return 'number'
    if kind == 'string':
        return 'string'
    if kind == 'boolean':
        return 'boolean'
    raise ValueError(f'Unsupported Scene schema node: {schema!r}')


def render(source_bytes):
    schema = json.loads(source_bytes)
    digest = hashlib.sha256(source_bytes).hexdigest()
    lines = [f'// Generated by scripts/generate_scene_types.py from slide_scene_v1.schema.json (SHA-256 {digest}).',
             '// Do not edit manually. These describe normalized server responses (defaults materialized).', '']
    for name, definition in schema['$defs'].items():
        lines.append(f'export type {name} = {type_for(definition)};')
        lines.append('')
    root = {key: value for key, value in schema.items() if key != '$defs'}
    lines.append(f'export type SlideScene = {type_for(root)};')
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='fail if generated types are stale')
    args = parser.parse_args()
    expected = render(SOURCE.read_bytes())
    if args.check:
        if not TARGET.is_file() or TARGET.read_text(encoding='utf-8') != expected:
            raise SystemExit('Scene TypeScript types are stale; run scripts/generate_scene_types.py')
    else:
        TARGET.write_text(expected, encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
