"""template import task metadata

Revision ID: 846e029db996
Revises: fb8af5ca2354
Create Date: 2026-10-02 09:42:54.605013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '846e029db996'
down_revision = 'fb8af5ca2354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_documents', sa.Column('selected_page_indexes_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('template_documents', sa.Column('import_task_id', sa.String(length=36), nullable=True))
    op.add_column('template_documents', sa.Column('error_code', sa.String(length=80), nullable=True))
    op.add_column('template_documents', sa.Column('error_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError('Template import task state may exist; do not destructively downgrade')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_documents', 'error_details')
    op.drop_column('template_documents', 'error_code')
    op.drop_column('template_documents', 'import_task_id')
    op.drop_column('template_documents', 'selected_page_indexes_json')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    # ### end Alembic commands ###
