"""scene v1 data model

Revision ID: 9ca530de35fb
Revises: c42f8e9a1b70
Create Date: 2026-10-02 09:06:40.250168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ca530de35fb'
down_revision = 'c42f8e9a1b70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('external_issuer', sa.String(length=255), nullable=True),
    sa.Column('external_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_issuer', 'external_subject')
    )
    op.create_table('api_idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'operation', 'idempotency_key')
    )
    op.create_table('model_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('provider_kind', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('key_suffix', sa.String(length=8), nullable=False),
    sa.Column('encrypted_secret', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.String(length=32), nullable=False),
    sa.Column('secret_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('capabilities_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_credentials_owner_id'), 'model_credentials', ['owner_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('source_asset_id', sa.String(length=36), nullable=True),
    sa.Column('provenance_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_table('deck_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=False),
    sa.Column('manifest_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_snapshots_project_id'), 'deck_snapshots', ['project_id'], unique=False)
    op.create_table('generation_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('base_project_version', sa.BigInteger(), nullable=False),
    sa.Column('manifest_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_plans_project_id'), 'generation_plans', ['project_id'], unique=False)
    op.create_table('scene_task_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('input_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fence_token', sa.BigInteger(), nullable=False),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_task_items_state'), 'scene_task_items', ['state'], unique=False)
    op.create_table('scene_exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('options_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('options_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('file_asset_id', sa.String(length=36), nullable=True),
    sa.Column('report_asset_id', sa.String(length=36), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['report_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['deck_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_asset_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('warnings_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('renderer_manifest_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_scene_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('parent_revision_id', sa.String(length=36), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('scene_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scene_hash', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('generation_plan_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('validation_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['generation_plan_id'], ['generation_plans.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['parent_revision_id'], ['page_scene_revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'seq')
    )
    op.create_index(op.f('ix_page_scene_revisions_page_id'), 'page_scene_revisions', ['page_id'], unique=False)
    op.create_table('revision_assets',
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['page_scene_revisions.id'], ),
    sa.PrimaryKeyConstraint('revision_id', 'asset_id', 'role')
    )
    op.create_table('scene_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_revision_id', sa.String(length=36), nullable=False),
    sa.Column('base_revision_id', sa.String(length=36), nullable=True),
    sa.Column('base_page_version', sa.BigInteger(), nullable=False),
    sa.Column('generation_plan_id', sa.String(length=36), nullable=True),
    sa.Column('scope_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('change_summary_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['generation_plan_id'], ['generation_plans.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['proposed_revision_id'], ['page_scene_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_candidates_project_id'), 'scene_candidates', ['project_id'], unique=False)
    op.create_table('snapshot_pages',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['page_scene_revisions.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['deck_snapshots.id'], ),
    sa.PrimaryKeyConstraint('snapshot_id', 'ordinal'),
    sa.UniqueConstraint('snapshot_id', 'page_id')
    )
    op.add_column('pages', sa.Column('head_revision_id', sa.String(length=36), nullable=True))
    op.add_column('pages', sa.Column('row_version', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('pages', sa.Column('next_scene_seq', sa.BigInteger(), server_default='1', nullable=False))
    op.add_column('pages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('owner_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('editor_mode', sa.String(length=20), server_default='legacy_image', nullable=False))
    op.add_column('projects', sa.Column('row_version', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('projects', sa.Column('canvas_width_pt', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('canvas_height_pt', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('projects', sa.Column('font_manifest_id', sa.String(length=64), nullable=True))
    op.add_column('projects', sa.Column('active_plan_id', sa.String(length=36), nullable=True))
    op.add_column('projects', sa.Column('model_config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.execute(sa.text("INSERT INTO principals (id, kind, display_name, status, created_at) VALUES ('00000000-0000-4000-8000-000000000001', 'local_owner', 'Local owner', 'active', CURRENT_TIMESTAMP)"))
    op.execute(sa.text("UPDATE projects SET owner_id = '00000000-0000-4000-8000-000000000001' WHERE owner_id IS NULL"))
    if op.get_bind().dialect.name != 'sqlite':
        op.create_foreign_key('fk_projects_owner_id', 'projects', 'principals', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError('Scene v1 data may exist; back up and migrate explicitly before downgrade')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'model_config_json')
    op.drop_column('projects', 'active_plan_id')
    op.drop_column('projects', 'font_manifest_id')
    op.drop_column('projects', 'canvas_height_pt')
    op.drop_column('projects', 'canvas_width_pt')
    op.drop_column('projects', 'row_version')
    op.drop_column('projects', 'editor_mode')
    op.drop_column('projects', 'owner_id')
    op.drop_column('pages', 'deleted_at')
    op.drop_column('pages', 'next_scene_seq')
    op.drop_column('pages', 'row_version')
    op.drop_column('pages', 'head_revision_id')
    op.drop_table('snapshot_pages')
    op.drop_index(op.f('ix_scene_candidates_project_id'), table_name='scene_candidates')
    op.drop_table('scene_candidates')
    op.drop_table('revision_assets')
    op.drop_index(op.f('ix_page_scene_revisions_page_id'), table_name='page_scene_revisions')
    op.drop_table('page_scene_revisions')
    op.drop_table('template_documents')
    op.drop_table('scene_exports')
    op.drop_index(op.f('ix_scene_task_items_state'), table_name='scene_task_items')
    op.drop_table('scene_task_items')
    op.drop_index(op.f('ix_generation_plans_project_id'), table_name='generation_plans')
    op.drop_table('generation_plans')
    op.drop_index(op.f('ix_deck_snapshots_project_id'), table_name='deck_snapshots')
    op.drop_table('deck_snapshots')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_model_credentials_owner_id'), table_name='model_credentials')
    op.drop_table('model_credentials')
    op.drop_table('api_idempotency_records')
    op.drop_table('principals')
    # ### end Alembic commands ###
