"""scene task attempts

Revision ID: ada32b22b76b
Revises: 9ca530de35fb
Create Date: 2026-10-02 09:27:34.334886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ada32b22b76b'
down_revision = '9ca530de35fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_task_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_item_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('fence_token', sa.BigInteger(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('dispatch_state', sa.String(length=24), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('usage_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['task_item_id'], ['scene_task_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_item_id', 'attempt_no')
    )
    op.add_column('scene_task_items', sa.Column('page_id', sa.String(length=36), nullable=True))
    op.add_column('scene_task_items', sa.Column('credential_id', sa.String(length=36), nullable=True))
    op.add_column('scene_task_items', sa.Column('logical_key', sa.String(length=120), nullable=True))
    op.add_column('scene_task_items', sa.Column('group_id', sa.String(length=36), nullable=True))
    op.add_column('scene_task_items', sa.Column('max_attempts', sa.Integer(), server_default='2', nullable=False))
    op.add_column('scene_task_items', sa.Column('dispatch_state', sa.String(length=24), server_default='not_sent', nullable=False))
    op.add_column('scene_task_items', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scene_task_items', sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scene_task_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute(sa.text('UPDATE scene_task_items SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL'))
    op.create_index(op.f('ix_scene_task_items_group_id'), 'scene_task_items', ['group_id'], unique=False)
    with op.batch_alter_table('scene_task_items') as batch:
        batch.alter_column('updated_at', nullable=False)
        batch.create_unique_constraint('uq_scene_task_group_key', ['group_id', 'logical_key'])
        batch.create_foreign_key('fk_scene_task_page', 'pages', ['page_id'], ['id'])
        batch.create_foreign_key('fk_scene_task_credential', 'model_credentials', ['credential_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError('Scene task history may exist; do not destructively downgrade')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scene_task_items', type_='foreignkey')
    op.drop_constraint(None, 'scene_task_items', type_='foreignkey')
    op.drop_constraint(None, 'scene_task_items', type_='unique')
    op.drop_index(op.f('ix_scene_task_items_group_id'), table_name='scene_task_items')
    op.drop_column('scene_task_items', 'updated_at')
    op.drop_column('scene_task_items', 'cancel_requested_at')
    op.drop_column('scene_task_items', 'next_run_at')
    op.drop_column('scene_task_items', 'dispatch_state')
    op.drop_column('scene_task_items', 'max_attempts')
    op.drop_column('scene_task_items', 'group_id')
    op.drop_column('scene_task_items', 'logical_key')
    op.drop_column('scene_task_items', 'credential_id')
    op.drop_column('scene_task_items', 'page_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_table('scene_task_attempts')
    # ### end Alembic commands ###
