"""template document references

Revision ID: fb8af5ca2354
Revises: ada32b22b76b
Create Date: 2026-10-02 09:38:19.214519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8af5ca2354'
down_revision = 'ada32b22b76b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_template_assets', sa.Column('template_document_id', sa.String(length=36), nullable=True))
    op.add_column('project_template_assets', sa.Column('preview_asset_id', sa.String(length=36), nullable=True))
    op.add_column('project_template_assets', sa.Column('thumbnail_asset_id', sa.String(length=36), nullable=True))
    op.add_column('project_template_assets', sa.Column('analysis_schema_version', sa.Integer(), nullable=True))
    op.add_column('project_template_assets', sa.Column('analysis_revision', sa.Integer(), server_default='0', nullable=False))
    op.add_column('project_template_assets', sa.Column('analysis_hash', sa.String(length=64), nullable=True))
    op.add_column('project_template_assets', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    with op.batch_alter_table('project_template_assets') as batch:
        batch.create_foreign_key('fk_template_document', 'template_documents', ['template_document_id'], ['id'])
        batch.create_foreign_key('fk_template_thumb_asset', 'assets', ['thumbnail_asset_id'], ['id'])
        batch.create_foreign_key('fk_template_preview_asset', 'assets', ['preview_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError('Template document references may exist; do not destructively downgrade')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'project_template_assets', type_='foreignkey')
    op.drop_constraint(None, 'project_template_assets', type_='foreignkey')
    op.drop_constraint(None, 'project_template_assets', type_='foreignkey')
    op.drop_column('project_template_assets', 'deleted_at')
    op.drop_column('project_template_assets', 'analysis_hash')
    op.drop_column('project_template_assets', 'analysis_revision')
    op.drop_column('project_template_assets', 'analysis_schema_version')
    op.drop_column('project_template_assets', 'thumbnail_asset_id')
    op.drop_column('project_template_assets', 'preview_asset_id')
    op.drop_column('project_template_assets', 'template_document_id')
    # ### end Alembic commands ###
